name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Kanan.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        Set-Alias -Name msbuild -Value 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe'
        $env:VCTargetsPath = 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v150'
        msbuild ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KananMabiPro
        path: |
          Release\dsound.dll
          Release\Patches.json